// <auto-generated />
namespace MentorIT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_Name1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Name1));
        
        string IMigrationMetadata.Id
        {
            get { return "201906061054485_User_Name1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
